"""fds

Revision ID: 58638e2cd76d
Revises: d3d99ce468fc
Create Date: 2022-08-10 12:51:53.384345

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58638e2cd76d'
down_revision = 'd3d99ce468fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.alter_column('message', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message', 'creation_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_column('chat', 'last_update')
    # ### end Alembic commands ###
