"""afsd

Revision ID: f70c07eac466
Revises: 5547ef633065
Create Date: 2022-08-07 18:53:38.722800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70c07eac466'
down_revision = '5547ef633065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user_image', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'image_id')
    # ### end Alembic commands ###
