"""ads

Revision ID: fb7a1c821bee
Revises: 7d835dce46ad
Create Date: 2022-08-05 13:09:06.794848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb7a1c821bee'
down_revision = '7d835dce46ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_id', sa.Integer(), nullable=True))
    op.drop_column('project', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_path', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('project', 'image_id')
    # ### end Alembic commands ###
